#! /bin/sh
# _____     __             _____               _  __ _
#|_   _|   / _|           |_   _|             (_)/ _( )
#  | | ___| |_ __ _ _ __    | | __ _ _   _ ___ _| |_|/ ___
#  | |/ __|  _/ _` | '__|   | |/ _` | | | / __| |  _| / __|
# _| |\__ \ || (_| | |      | | (_| | |_| \__ \ | |   \__ \
# \___/___/_| \__,_|_|      \_/\__,_|\__,_|___/_|_|   |___/
#______      _    __ _ _
#|  _  \    | |  / _(_) |
#| | | |___ | |_| |_ _| | ___  ___
#| | | / _ \| __|  _| | |/ _ \/ __|
#| |/ / (_) | |_| | | | |  __/\__ \
#|___/ \___/ \__|_| |_|_|\___||___/





# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
#picom
feh --bg-fill ~/.dotfiles/assets/wallpaper.jpg &
polybar rhymebar --config=~/.config/polybar/config.ini &

# Desktops
bspc monitor -d I II III IV V VI #VII VIII IX X





# ----------------- #
### C O N F I G S ###
# ----------------- #

bspc config border_width            2
bspc config window_gap              15
bspc config top_padding             15
bspc config split_ratio             0.50
bspc config normal_border_color     "#0e0e0e"
bspc config focused_border_color    "#1badff"
bspc config presel_feedback_color   "#1badff"

bspc config borderless_monocle  true
bspc config gapless_monocle     true





# ------------------------------------- #
### A P P L I C A T I O N - R U L E S ###
# ------------------------------------- #

#Fullscreen

#Tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#Floating
bspc rule -a mplayer2 state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on